//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap add_16 {
            get {
                object obj = ResourceManager.GetObject("add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap add_32 {
            get {
                object obj = ResourceManager.GetObject("add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap add1 {
            get {
                object obj = ResourceManager.GetObject("add1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap America_flag_16x16 {
            get {
                object obj = ResourceManager.GetObject("America_flag_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap App_16x16 {
            get {
                object obj = ResourceManager.GetObject("App_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap App_32x32 {
            get {
                object obj = ResourceManager.GetObject("App_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 KNX UI Editor 是一款用户界面定制工具，本工具定义界面的元素和位置，通过解析引擎动态的生成控制界面 的本地化字符串。
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KNX UI Editor 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Area_16x16 {
            get {
                object obj = ResourceManager.GetObject("Area_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Area_32x32 {
            get {
                object obj = ResourceManager.GetObject("Area_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap blinds {
            get {
                object obj = ResourceManager.GetObject("blinds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Button_16x16 {
            get {
                object obj = ResourceManager.GetObject("Button_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Check_32x32 {
            get {
                object obj = ResourceManager.GetObject("Check_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Chinese_flag_16x16 {
            get {
                object obj = ResourceManager.GetObject("Chinese_flag_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Close_16 {
            get {
                object obj = ResourceManager.GetObject("Close_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Close_32 {
            get {
                object obj = ResourceManager.GetObject("Close_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CloseProj_16 {
            get {
                object obj = ResourceManager.GetObject("CloseProj_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CloseProj_32 {
            get {
                object obj = ResourceManager.GetObject("CloseProj_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Collapse_16x16 {
            get {
                object obj = ResourceManager.GetObject("Collapse_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Collapse_32x32 {
            get {
                object obj = ResourceManager.GetObject("Collapse_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ColorPalette_16x16 {
            get {
                object obj = ResourceManager.GetObject("ColorPalette_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ColorPalette_32x32 {
            get {
                object obj = ResourceManager.GetObject("ColorPalette_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ZHUHAI SATION 的本地化字符串。
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap connection_16 {
            get {
                object obj = ResourceManager.GetObject("connection_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap connection_32 {
            get {
                object obj = ResourceManager.GetObject("connection_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Controls_16x16 {
            get {
                object obj = ResourceManager.GetObject("Controls_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Controls_32x32 {
            get {
                object obj = ResourceManager.GetObject("Controls_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Copy_16x16 {
            get {
                object obj = ResourceManager.GetObject("Copy_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Copy_16x161 {
            get {
                object obj = ResourceManager.GetObject("Copy_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ZHUHAI SATION 2012-2016 的本地化字符串。
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Cut_16x16 {
            get {
                object obj = ResourceManager.GetObject("Cut_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;MainNumber&quot;: 1,
        ///        &quot;Format&quot;: &quot;B1&quot;,
        ///        &quot;Size&quot;: &quot;1 Bit&quot;,
        ///        &quot;Subs&quot;: [
        ///            {
        ///                &quot;SubNumber&quot;: 1,
        ///                &quot;DPTName&quot;: &quot;Switch&quot;
        ///            },
        ///            {
        ///                &quot;SubNumber&quot;: 2,
        ///                &quot;DPTName&quot;: &quot;Bool&quot;
        ///            },
        ///            {
        ///                &quot;SubNumber&quot;: 3,
        ///                &quot;DPTName&quot;: &quot;Enable&quot;
        ///            },
        ///            {
        ///                &quot;SubNumber&quot;: 4,
        ///                &quot;DPTName&quot;: &quot;Ramp&quot;
        ///            },
        ///       [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DatapointType {
            get {
                return ResourceManager.GetString("DatapointType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap delete_16 {
            get {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap delete_32 {
            get {
                object obj = ResourceManager.GetObject("delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Delete_Control_16x16 {
            get {
                object obj = ResourceManager.GetObject("Delete_Control_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Delete_Control_32x32 {
            get {
                object obj = ResourceManager.GetObject("Delete_Control_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DigitalAdjustment_500x500 {
            get {
                object obj = ResourceManager.GetObject("DigitalAdjustment_500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Edit_16 {
            get {
                object obj = ResourceManager.GetObject("Edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Edit_32 {
            get {
                object obj = ResourceManager.GetObject("Edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Expand_16x16 {
            get {
                object obj = ResourceManager.GetObject("Expand_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Expand_32x32 {
            get {
                object obj = ResourceManager.GetObject("Expand_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Export_32x32 {
            get {
                object obj = ResourceManager.GetObject("Export_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Grid_16x16 {
            get {
                object obj = ResourceManager.GetObject("Grid_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Grid_32x32 {
            get {
                object obj = ResourceManager.GetObject("Grid_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Help_16x16 {
            get {
                object obj = ResourceManager.GetObject("Help_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Help_32x32 {
            get {
                object obj = ResourceManager.GetObject("Help_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_helper {
            get {
                object obj = ResourceManager.GetObject("icon_helper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IconSwitchButton {
            get {
                object obj = ResourceManager.GetObject("IconSwitchButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap imageButton {
            get {
                object obj = ResourceManager.GetObject("imageButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImportKNX_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImportKNX_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImportKNX_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImportKNX_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Info_16x16 {
            get {
                object obj = ResourceManager.GetObject("Info_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Info_32x32 {
            get {
                object obj = ResourceManager.GetObject("Info_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap label {
            get {
                object obj = ResourceManager.GetObject("label", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Label_16x16 {
            get {
                object obj = ResourceManager.GetObject("Label_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap media_button {
            get {
                object obj = ResourceManager.GetObject("media_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 文件已经修改，是否要保存？ 的本地化字符串。
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到启动程序 : 的本地化字符串。
        /// </summary>
        internal static string Message10 {
            get {
                return ResourceManager.GetString("Message10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目发布不成功 ! 的本地化字符串。
        /// </summary>
        internal static string Message11 {
            get {
                return ResourceManager.GetString("Message11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群组加载错误 ! 的本地化字符串。
        /// </summary>
        internal static string Message12 {
            get {
                return ResourceManager.GetString("Message12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型不兼容，不能粘贴到当前的节点 ! 的本地化字符串。
        /// </summary>
        internal static string Message13 {
            get {
                return ResourceManager.GetString("Message13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你是否要删除当前节点 ? 的本地化字符串。
        /// </summary>
        internal static string Message14 {
            get {
                return ResourceManager.GetString("Message14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除节点提醒 的本地化字符串。
        /// </summary>
        internal static string Message15 {
            get {
                return ResourceManager.GetString("Message15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本： {0} 的本地化字符串。
        /// </summary>
        internal static string Message16 {
            get {
                return ResourceManager.GetString("Message16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件保存提醒 的本地化字符串。
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据! 的本地化字符串。
        /// </summary>
        internal static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示信息 的本地化字符串。
        /// </summary>
        internal static string Message4 {
            get {
                return ResourceManager.GetString("Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统异常 的本地化字符串。
        /// </summary>
        internal static string Message5 {
            get {
                return ResourceManager.GetString("Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误提示 的本地化字符串。
        /// </summary>
        internal static string Message6 {
            get {
                return ResourceManager.GetString("Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前项目未保存，是否先将当前项目保存 ? 的本地化字符串。
        /// </summary>
        internal static string Message7 {
            get {
                return ResourceManager.GetString("Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目文件不兼容 ! 的本地化字符串。
        /// </summary>
        internal static string Message8 {
            get {
                return ResourceManager.GetString("Message8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到项目文件 : 的本地化字符串。
        /// </summary>
        internal static string Message9 {
            get {
                return ResourceManager.GetString("Message9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MoveDown_16x16 {
            get {
                object obj = ResourceManager.GetObject("MoveDown_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MoveDown_32x32 {
            get {
                object obj = ResourceManager.GetObject("MoveDown_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MoveUp_16x16 {
            get {
                object obj = ResourceManager.GetObject("MoveUp_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MoveUp_32x32 {
            get {
                object obj = ResourceManager.GetObject("MoveUp_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap New_16x16 {
            get {
                object obj = ResourceManager.GetObject("New_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap New_32x32 {
            get {
                object obj = ResourceManager.GetObject("New_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Open_16x16 {
            get {
                object obj = ResourceManager.GetObject("Open_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Open_32x32 {
            get {
                object obj = ResourceManager.GetObject("Open_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Page_16x16 {
            get {
                object obj = ResourceManager.GetObject("Page_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Page_32x32 {
            get {
                object obj = ResourceManager.GetObject("Page_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Paste_16x16 {
            get {
                object obj = ResourceManager.GetObject("Paste_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不透明度 的本地化字符串。
        /// </summary>
        internal static string PropAlpha {
            get {
                return ResourceManager.GetString("PropAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序说明 的本地化字符串。
        /// </summary>
        internal static string PropAppDesc {
            get {
                return ResourceManager.GetString("PropAppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色 的本地化字符串。
        /// </summary>
        internal static string PropBackColor {
            get {
                return ResourceManager.GetString("PropBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景图片 的本地化字符串。
        /// </summary>
        internal static string PropBackgroundImage {
            get {
                return ResourceManager.GetString("PropBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件是否可以点击 的本地化字符串。
        /// </summary>
        internal static string PropClickable {
            get {
                return ResourceManager.GetString("PropClickable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业Logo 的本地化字符串。
        /// </summary>
        internal static string PropComLogo {
            get {
                return ResourceManager.GetString("PropComLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数位数 的本地化字符串。
        /// </summary>
        internal static string PropDecimalDigits {
            get {
                return ResourceManager.GetString("PropDecimalDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值 的本地化字符串。
        /// </summary>
        internal static string PropDefaultValue {
            get {
                return ResourceManager.GetString("PropDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字位数 的本地化字符串。
        /// </summary>
        internal static string PropDigitalNumber {
            get {
                return ResourceManager.GetString("PropDigitalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示值 的本地化字符串。
        /// </summary>
        internal static string PropDisplayValue {
            get {
                return ResourceManager.GetString("PropDisplayValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ETS读地址 的本地化字符串。
        /// </summary>
        internal static string PropEtsReadAddressId {
            get {
                return ResourceManager.GetString("PropEtsReadAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ETS写地址表 的本地化字符串。
        /// </summary>
        internal static string PropEtsWriteAddressIds {
            get {
                return ResourceManager.GetString("PropEtsWriteAddressIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平面样式 的本地化字符串。
        /// </summary>
        internal static string PropFlatStyle {
            get {
                return ResourceManager.GetString("PropFlatStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体颜色 的本地化字符串。
        /// </summary>
        internal static string PropFontColor {
            get {
                return ResourceManager.GetString("PropFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体大小 的本地化字符串。
        /// </summary>
        internal static string PropFontSize {
            get {
                return ResourceManager.GetString("PropFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有提示 的本地化字符串。
        /// </summary>
        internal static string PropHasTip {
            get {
                return ResourceManager.GetString("PropHasTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度(像素) 的本地化字符串。
        /// </summary>
        internal static string PropHeight {
            get {
                return ResourceManager.GetString("PropHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        internal static string PropIcon {
            get {
                return ResourceManager.GetString("PropIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否为默认房间 的本地化字符串。
        /// </summary>
        internal static string PropIsDefaultRoom {
            get {
                return ResourceManager.GetString("PropIsDefaultRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否属于组 的本地化字符串。
        /// </summary>
        internal static string PropIsGroup {
            get {
                return ResourceManager.GetString("PropIsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左侧图片 的本地化字符串。
        /// </summary>
        internal static string PropLeftImage {
            get {
                return ResourceManager.GetString("PropLeftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左标签 的本地化字符串。
        /// </summary>
        internal static string PropLeftText {
            get {
                return ResourceManager.GetString("PropLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大值 的本地化字符串。
        /// </summary>
        internal static string PropMax {
            get {
                return ResourceManager.GetString("PropMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计量单位 的本地化字符串。
        /// </summary>
        internal static string PropMeasurementUnit {
            get {
                return ResourceManager.GetString("PropMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值 的本地化字符串。
        /// </summary>
        internal static string PropMin {
            get {
                return ResourceManager.GetString("PropMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string PropPassword {
            get {
                return ResourceManager.GetString("PropPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆角半径 的本地化字符串。
        /// </summary>
        internal static string PropRadius {
            get {
                return ResourceManager.GetString("PropRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右侧图片 的本地化字符串。
        /// </summary>
        internal static string PropRightImage {
            get {
                return ResourceManager.GetString("PropRightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右标签 的本地化字符串。
        /// </summary>
        internal static string PropRightText {
            get {
                return ResourceManager.GetString("PropRightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滑动图片 的本地化字符串。
        /// </summary>
        internal static string PropSlideImage {
            get {
                return ResourceManager.GetString("PropSlideImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭时控件背景色 的本地化字符串。
        /// </summary>
        internal static string PropSwitchColorOff {
            get {
                return ResourceManager.GetString("PropSwitchColorOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启时控件背景色 的本地化字符串。
        /// </summary>
        internal static string PropSwitchColorOn {
            get {
                return ResourceManager.GetString("PropSwitchColorOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭时显示的图片 的本地化字符串。
        /// </summary>
        internal static string PropSwitchImageOff {
            get {
                return ResourceManager.GetString("PropSwitchImageOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启时显示的图片 的本地化字符串。
        /// </summary>
        internal static string PropSwitchImageOn {
            get {
                return ResourceManager.GetString("PropSwitchImageOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示文字 的本地化字符串。
        /// </summary>
        internal static string PropTip {
            get {
                return ResourceManager.GetString("PropTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string PropTitle {
            get {
                return ResourceManager.GetString("PropTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象类型 的本地化字符串。
        /// </summary>
        internal static string PropType {
            get {
                return ResourceManager.GetString("PropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度(像素) 的本地化字符串。
        /// </summary>
        internal static string PropWidth {
            get {
                return ResourceManager.GetString("PropWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X(水平起始) 的本地化字符串。
        /// </summary>
        internal static string PropX {
            get {
                return ResourceManager.GetString("PropX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y(垂直起始) 的本地化字符串。
        /// </summary>
        internal static string PropY {
            get {
                return ResourceManager.GetString("PropY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Publish_16 {
            get {
                object obj = ResourceManager.GetObject("Publish_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RadioGroup_220x220 {
            get {
                object obj = ResourceManager.GetObject("RadioGroup_220x220", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Refresh_24 {
            get {
                object obj = ResourceManager.GetObject("Refresh_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap rgb {
            get {
                object obj = ResourceManager.GetObject("rgb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Room_16x16 {
            get {
                object obj = ResourceManager.GetObject("Room_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Save_16x16 {
            get {
                object obj = ResourceManager.GetObject("Save_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Save_32x32 {
            get {
                object obj = ResourceManager.GetObject("Save_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap scene_button {
            get {
                object obj = ResourceManager.GetObject("scene_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap search_16 {
            get {
                object obj = ResourceManager.GetObject("search_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap search_32 {
            get {
                object obj = ResourceManager.GetObject("search_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sip2 {
            get {
                object obj = ResourceManager.GetObject("sip2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap slider {
            get {
                object obj = ResourceManager.GetObject("slider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Slider_16 {
            get {
                object obj = ResourceManager.GetObject("Slider_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Slider_16x16 {
            get {
                object obj = ResourceManager.GetObject("Slider_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap slider_switch {
            get {
                object obj = ResourceManager.GetObject("slider_switch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap snapper {
            get {
                object obj = ResourceManager.GetObject("snapper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap snapper_switch {
            get {
                object obj = ResourceManager.GetObject("snapper_switch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SortAsc_16x16 {
            get {
                object obj = ResourceManager.GetObject("SortAsc_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SortAsc_32x32 {
            get {
                object obj = ResourceManager.GetObject("SortAsc_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SortDesc_16x16 {
            get {
                object obj = ResourceManager.GetObject("SortDesc_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SortDesc_32x32 {
            get {
                object obj = ResourceManager.GetObject("SortDesc_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap switch_16x16 {
            get {
                object obj = ResourceManager.GetObject("switch_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        internal static string SwitchStateOff {
            get {
                return ResourceManager.GetString("SwitchStateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        internal static string SwitchStateOn {
            get {
                return ResourceManager.GetString("SwitchStateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序 的本地化字符串。
        /// </summary>
        internal static string TextApplication {
            get {
                return ResourceManager.GetString("TextApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域 的本地化字符串。
        /// </summary>
        internal static string TextArea {
            get {
                return ResourceManager.GetString("TextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗帘控制 的本地化字符串。
        /// </summary>
        internal static string TextBlinds {
            get {
                return ResourceManager.GetString("TextBlinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字调节 的本地化字符串。
        /// </summary>
        internal static string TextDigitalAdjustment {
            get {
                return ResourceManager.GetString("TextDigitalAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组框 的本地化字符串。
        /// </summary>
        internal static string TextGroupBox {
            get {
                return ResourceManager.GetString("TextGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string TextLabel {
            get {
                return ResourceManager.GetString("TextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面 的本地化字符串。
        /// </summary>
        internal static string TextPage {
            get {
                return ResourceManager.GetString("TextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间 的本地化字符串。
        /// </summary>
        internal static string TextRoom {
            get {
                return ResourceManager.GetString("TextRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景按钮 的本地化字符串。
        /// </summary>
        internal static string TextSceneButton {
            get {
                return ResourceManager.GetString("TextSceneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滑动开关 的本地化字符串。
        /// </summary>
        internal static string TextSliderSwitch {
            get {
                return ResourceManager.GetString("TextSliderSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开关 的本地化字符串。
        /// </summary>
        internal static string TextSwitch {
            get {
                return ResourceManager.GetString("TextSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定时器 的本地化字符串。
        /// </summary>
        internal static string TextTimer {
            get {
                return ResourceManager.GetString("TextTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据显示 的本地化字符串。
        /// </summary>
        internal static string TextValueDisplay {
            get {
                return ResourceManager.GetString("TextValueDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap timer_512x512 {
            get {
                object obj = ResourceManager.GetObject("timer_512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap timer_task_list {
            get {
                object obj = ResourceManager.GetObject("timer_task_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap value_display {
            get {
                object obj = ResourceManager.GetObject("value_display", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap webcam_viewer {
            get {
                object obj = ResourceManager.GetObject("webcam_viewer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
